from pydantic import BaseModel, EmailStr, Field
from typing import Optional

class AddressSchema(BaseModel):
    street: str = Field(..., description="Flat/House No, Colony, Street layout")
    city: str = Field(..., description="City name")
    state: str = Field(..., description="State name")
    pincode: str = Field(..., description="6-digit postal pincode")
    country: str = Field(default="India")

class PersonalDetails(BaseModel):
    full_name: str = Field(..., description="Student's legal name")
    email: EmailStr = Field(..., description="Primary student communication email")
    mobile_no: str = Field(..., description="Verified phone number with country code")
    address: AddressSchema

class ParentDetails(BaseModel):
    parent_name: str = Field(..., description="Parent or legal guardian name")
    parent_mobile: str = Field(..., description="Parent contact number for subscription updates")
    parent_email: Optional[EmailStr] = None

class AcademicProfile(BaseModel):
    current_grade: str = Field(..., description="Active school standard, e.g., '10'")
    school_board: str = Field(default="CBSE", description="Curriculum board, e.g., CBSE, ICSE")
    school_name: str = Field(..., description="Name of the school")
    default_teaching_language: str = Field(default="en-IN", description="Preferred learning medium, e.g., 'hi-IN'")

class StudentSignupRequest(BaseModel):
    uid: str = Field(..., description="The unique identity token generated by Firebase Phone Auth upon verification")
    personal_details: PersonalDetails
    parent_details: ParentDetails
    academic_profile: AcademicProfile